### ISSUE TITLE
Change target address for fees ratio 

### ISSUE THREAD

**Issue by mtbitcoin** [ppratscher/etherreg#1]
I propose changing the :

fees[owner1] = names[name].bid / 2;
fees[owner2] = names[name].bid / 2;

And instead sending the fees collected to a single external multi-sig wallet contract instead. The ratios/split can then be handled outside of the main etherreg contract. This will allow the flexibility of redirecting future payments and changing ratios if necessary

**Comment by peterbitfly** [comment]
In addition we need to add the functionality that each change in regards to fee distribution needs to be signed off by both of us. This will add a bit of complexity to the contract.

**Comment by mtbitcoin** [comment]
we can keep it simple for now, if its add complexity
